name: uuid
description: IETF UUIDs (primarily Version 4)
version: 0.6.3

author: Jim Philbin <mailto:jfphilbin@gmail.com>

homepage: https://github.com/OpenDICOMweb/uuid

environment:
  sdk: '>=1.24.2 <2.0.0'

dependencies:
  string:
    path: C:/odw/sdk/string
    version: ^0.6.3
  system:
    path: C:/odw/sdk/system
    version: ^0.6.3


dev_dependencies:
  benchmark_harness: ^1.0.4
  grinder: ^0.8.0

  test:  ^0.12.0
