name: uuid
description: DICOM UIDs
version: 0.6.1

author: Jim Philbin <mailto:jfphilbin@gmail.com>

homepage: https://github.com/OpenDICOMweb/uid

environment:
  sdk: '>=1.24.2 <2.0.0'

#dependencies:


dev_dependencies:
  benchmark_harness: ^1.0.4
  grinder: ^0.8.0
  system:
    path: C:/odw/sdk/system
    version: ^0.6.0
  test:  ^0.12.0
